const text = [
  `Jelly sweet roll jelly beans biscuit pie macaroon chocolate donut. Carrot cake caramels pie sweet apple pie tiramisu carrot cake. Marzipan marshmallow croissant tootsie roll lollipop. Cupcake lemon drops bear claw gummies. Jelly bear claw gummi bears lollipop cotton candy gummi bears chocolate bar cake cookie. Cupcake muffin danish muffin cookie gummies. Jelly beans tiramisu pudding. Toffee soufflé chocolate cake pastry brownie. Oat cake halvah sweet roll cotton candy croissant lollipop. Macaroon tiramisu chocolate bar candy candy carrot cake jelly sweet. Gummies croissant macaroon dessert. Chocolate cake dragée pie.`,
  `Next level tbh everyday carry, blog copper mug forage kitsch roof party pickled hammock kale chips tofu. Etsy shoreditch 8-bit microdosing, XOXO viral butcher banh mi humblebrag listicle woke bicycle rights brunch before they sold out ramps. Twee shabby chic taiyaki flannel, enamel pin venmo vape four loko. Hexagon kale chips typewriter kitsch 8-bit organic plaid small batch keffiyeh ethical banh mi narwhal echo park cronut.`,
  `Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.`,
  `Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
  `This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them.
I just told you! You've killed me! Fry! Quit doing the right thing, you jerk! Michelle, I don't regret this, but I both rue and lament it. Morbo can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.`,
  `Airedale hard cheese mozzarella. Pecorino melted cheese port-salut emmental babybel cheese and wine melted cheese manchego. Everyone loves blue castello everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian bergkase who moved my cheese halloumi port-salut gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
  `Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key meggings vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth. Snackwave raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray chicharrones cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe bushwick kitsch tumeric cloud bread vaporware freegan franzen pork belly chicharrones banh mi.`,
  `Man braid celiac synth freegan readymade, pitchfork fam salvia waistcoat lomo bitters gentrify four loko. Pitchfork semiotics post-ironic vegan. Tofu meditation microdosing hashtag semiotics venmo. Flexitarian vape tilde taiyaki. Prism poutine farm-to-table, messenger bag vegan taxidermy tattooed sartorial squid jean shorts fixie selvage trust fund vape.`,
  `Rutters Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,
  `Webtwo ipsum chartly voki zynga yuntaa grockit, napster geni zimbra. Jibjab dopplr geni hulu wikia tumblr, glogster divvyshot etsy. Twones koofers vuvox flickr, wesabe sifteo. zoodles zapier waze. balihoo orkut yuntaa. Convore ning jiglu whrrl eskobo, sclipo yuntaa chartly. Stypi zappos oovoo heroku akismet wufoo weebly glogster ngmoco, babblely mog revver wakoopa blyve etsy. Oooooc kazaa eduvant dopplr sclipo, ebay ning. Vimeo scribd lanyrd cuil doostang, hojoki zoho fleck greplin, palantir orkut eskobo. Koofers akismet eskobo ifttt waze ngmoco, skype greplin trulia nuvvo. Kno rovio sifteo dropio chegg, yoono gsnap. Imeem zoho balihoo napster spock zlio, nuvvo jaiku hojoki voxy.`,
  `Bebo eduvant edmodo loopt nuvvo, rovio waze kaboodle. Squidoo unigo hojoki akismet, flickr zoosk zoodles, blippy joukuu. Unigo zimbra boxbe reddit gsnap octopart, ifttt zooomr glogster joukuu orkut kosmix, bitly koofers wikia shopify.`,
  `Vimeo voki imeem zoho, zlio ifttt jiglu zappos, mog ebay. Octopart vuvox gsnap zapier weebly, eskobo dogster vimeo. Mobly bubbli napster airbnb oovoo fleck, zoho jumo woopra palantir. Zillow vimeo babblely jaiku lala kiko, diigo xobni wufoo. Oooooc joukuu klout divvyshot joyent, jiglu plugg. Weebly hipmunk ngmoco loopt rovio zapier diigo cotweet, spock ifttt orkut squidoo movity weebly. Groupon spock gooru ifttt shopify, zynga odeo. Tumblr zapier weebly twitter kno, ideeli gooru.`,
  `Wufoo groupon cloudera glogster meebo kosmix, qeyno grockit jajah cloudera. Sclipo disqus joyent nuvvo zappos eduvant zinch, zoosk weebly ifttt sifteo. Kosmix airbnb groupon mozy qeyno kazaa grockit disqus, kazaa heroku zimbra shopify kippt. Mog hojoki mozy airbnb, voki wikia. Yammer qeyno joukuu ngmoco, jaiku. cuil yoono edmodo. Bubbli joost boxbe cuil jumo, twitter spock. Vuvox plaxo nuvvo ideeli plickers, bubbli kiko meevee, hipmunk zlio lanyrd. Quora zoosk yoono lala waze twones kippt plugg, dogster palantir whrrl zynga twones elgg.`,
  `Spotify reddit balihoo omgpop sococo kippt, dropio ning ebay wesabe, joost jiglu wakoopa twones. Ning zooomr chartly vuvox knewton, heroku klout. Waze oovoo unigo tivo mozy joukuu, blekko zynga kaboodle. Octopart odeo tumblr chartly convore, chumby edmodo.  Edmodo wikia ideeli jaiku, oovoo elgg. Meebo divvyshot sifteo omgpop mozy, joyent odeo vimeo, plaxo mzinga edmodo. Palantir zillow airbnb joyent gsnap, jabber trulia meebo. Jaiku hulu twitter boxbe twitter, joost airbnb. Vuvox skype zappos, spotify. Hulu imvu dropio foodzie joyent lala, elgg weebly chumby jaiku. Qeyno mzinga jabber ideeli, empressr jabber.`,
  `Zapier waze napster omgpop, diigo convore. Fleck plugg flickr appjet weebly, sifteo oooj appjet. Dopplr ngmoco tumblr akismet, edmodo zillow.  Boxbe zanga udemy vuvox, tumblr jiglu. Quora chegg vimeo tumblr diigo, sclipo zoho.`,
  `Lala trulia mog oovoo, ning lijit. Kno jajah sifteo twones empressr, kosmix joost plickers, insala airbnb kaboodle. Plickers udemy wufoo spock, akismet. Zoosk imvu jajah zinch, sococo. Hulu prezi bitly jumo ebay, yoono chegg. Imvu vimeo heekya scribd knewton whrrl, qeyno fleck xobni. Hipmunk klout jajah hulu xobni, jibjab kno.`,
  `Rovio reddit xobni unigo spotify, yuntaa zillow. Lijit rovio akismet weebly handango, trulia jajah. Jumo jabber gsnap meevee jibjab, hipmunk kosmix mobly. Lijit diigo blyve kosmix balihoo knewton prezi, elgg imeem divvyshot nuvvo babblely.`,
  `Ngmoco tivo etsy heroku foodzie, bitly plugg revver. Ngmoco greplin ifttt bubbli, oooooc handango weebly tivo, boxbe shopify. Etsy voxy orkut squidoo cloudera loopt, jibjab geni oooj. Dogster orkut sococo empressr zappos jabber voki wikia hipmunk, reddit vuvox empressr hojoki xobni cotweet edmodo.
`,
]
export default text
